<?php 
	//decode the outputBx and check if have confirmation 
	$oldLic = '';
	$spl = 'S1-P1';
	$sgn = 'G3N3R-4T3D';

	//procesos del download (decode/ check first split sipi serie in database if has license / register if hasnt license / download lic)
	if( isset($_POST['setClient']) ){
		//1
		$oldLic = base64_decode($_POST['setFullname']);
		$newLic = '';
		//2
		if(strpos($oldLic, $spl)){
			$pieces = explode($spl, $oldLic);
			if($pieces[0] != ""){
				//echo $pieces[0];
				//3
				require ("../database.php");

				$sql= "SELECT user, license FROM mobireptable WHERE user = '$pieces[0]'";	
							 	$columna1='';
							 	$columna2='';
							 	$stat = $conn->query($sql);
								while ($row = $stat->fetch_assoc()){ 	//procesar datos
									$columna1 = $row['user'];
									$columna2 = $row['license'];
								}

								if($columna1==$pieces[0]){	//verificar el nombre del usuario

									if($columna2 == NULL){
										//4
										//se registra 
										if($pieces[1]!=""){
											$sql = "UPDATE mobireptable SET license='$pieces[1]' WHERE user='$columna1'";
											if ($conn->query($sql)===TRUE) {
											    //5
											    //create the new token and create to txt to download it 
											    $newLic = base64_encode($pieces[0] . $spl . $pieces[1] . $sgn);
											    echo $newLic;
											    header('Content-Disposition: attachment; filename="License.txt"');
												header('Content-Type: text/plain'); 
												header('Content-Length: ' . strlen($newLic));
												header('Connection: close');
												return;
											} else {
											    echo 'Error, Registering The License';
											}
										}else{
											echo 'Error, This License Dont Have Request To Sign.';
										}

									}else{
										echo 'This User Have License Registered';
									}
									
								}else{
									//this user dont have serie nomber 
									echo 'Error, This User Dont Have Valid Product Serial.';
								
								}	
								echo "<br><br>";
								$conn->close();

			}
		}else{
			echo 'Error, This License Not Generated By The User In The MobiRep Application.';
			echo "<br><br>";
		}
	}

 ?>
<!DOCTYPE html>
<html>
<head>
	<link rel="icon" href="../../images/MobiRepLogo.png">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<title>MobiRepLicense</title>
</head>
<body>
	<p>Step 1: </p>
	  <input type="file" id="upload" class="file-upload">
	  
	  <br>

	  <hr style="border-top: 3px double #8c8b8b;">
    <p>Step 2: </p>
	    <form name="myform" action="" method="POST">
		    <label for="exampleInputEmail1">Please Download the verified License from the next button </label>
		    <br>
		    <input type="hidden" class="form-control" name="setFullname" placeholder="License" id="ciflic">
		    <br>
		    <br>
		  <button type="submit" name="setClient" class="btn btn-primary">Download Verified License</button>
		</form>

	<hr style="border-top: 3px double #8c8b8b;">

	<p>Step 3: Replace the new License.txt in the app forlder on you pc</p>
	<br>
		    <br>
	<hr style="border-top: 3px double #8c8b8b;">


	  <script src="MobiRepLicense.js"></script>
</body>
</html>